name: GitHub Readme Stats

on:
  schedule:
    - cron: "0 */6 * * *"  # Каждые 6 часов
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Readme Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          user_id: qqwozz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "docs: update readme stats [skip ci]"
          git push
